// auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/// tenants
export const SET_TENANTS = 'SET_TENANTS';
export const ADD_TENANT = 'ADD_TENANT';
export const REMOVE_TENANT = 'REMOVE_TENANT';
export const EDIT_TENANT = 'EDIT_TENANT';
export const LOADING_TENANTS = 'LOADING_TENANTS';
export const TENANTS_LOADED = 'TENANTS_LOADED';


 // voting
export const ADD_VOTING = 'ADD_VOTING';
export const SET_VOTING = 'SET_VOTING';
export const EDIT_VOTING = 'EDIT_VOTING';
export const LOADING_VOTES = 'LOADING_VOTES';
export const VOTES_LOADED = 'VOTES_LOADED';

// message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const LOADING_MESSAGES = 'LOADING_MESSAGES';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';

// issue
export const ADD_ISSUE = 'ADD_ISSUE';
export const SET_ISSUES = 'SET_ISSUES';
export const EDIT_ISSUE = 'EDIT_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE'
export const LOADING_ISSUES = 'LOADING_ISSUES';
export const ISSUES_LOADED = 'ISSUES_LOADED';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


/* filters */

// issue
export const SET_TEXT_FILTER_ISSUE = 'SET_TEXT_FILTER_ISSUE';
export const SORT_BY_DATE_ISSUE = 'SORT_BY_DATE_ISSUE';
export const SORT_BY_PRIORITY_ISSUE = 'SORT_BY_PRIORITY_ISSUE';
// export const SET_STATUS_FILTER_ISSUE = 'SET_STATUS_FILTER_ISSUE';

// message
export const SET_TEXT_FILTER_MESSAGE = 'SET_TEXT_FILTER_MESSAGE';
export const SORT_BY_DATE_MESSAGE = 'SORT_BY_DATE_MESSAGE';
export const SORT_BY_PRIORITY_MESSAGE = 'SORT_BY_PRIORITY_MESSAGE';
export const SET_PRIORITY_FILTER_MESSAGE = 'SET_PRIORITY_FILTER_MESSAGE';

// tenant
export const SET_TEXT_FILTER_TENANT = 'SET_TEXT_FILTER_TENANT';
export const SORT_BY_DATE_TENANT = 'SORT_BY_DATE_TENANT';
export const SORT_BY_PRIORITY_TENANT = 'SORT_BY_PRIORITY_TENANT';

// voting
export const SET_TEXT_FILTER_VOTING = 'SET_TEXT_FILTER_VOTING';
export const SET_STATUS_FILTER_VOTING = 'SET_STATUS_FILTER_VOTING';
export const SORT_BY_DATE_VOTING = 'SORT_BY_DATE_VOTING';
export const SORT_BY_PRIORITY_VOTING = 'SORT_BY_PRIORITY_VOTING';